#!/bin/bash
# Round 28: the desktop margins' art — sketchbook scraps, the flipbook's pencil test, the stickers.
#   scripts/gen-desk.sh [only-name ...]   → art/raw/<name>.png
cd "$(dirname "$0")/../art/raw" || exit 1
JOBS=${JOBS:-6}
ONLY=" $* "
want() { [ "$ONLY" = "  " ] || [[ "$ONLY" == *" $1 "* ]]; }
go() { local name=$1 prompt=$2; shift 2
  want "$name" || return; [ -f "$name.png" ] && return
  while [ "$(jobs -rp | wc -l)" -ge "$JOBS" ]; do sleep 2; done
  local imgs=(); for i in "$@"; do imgs+=("--image=$i"); done
  ( echo "== $name"
    timeout 1500 codex exec --skip-git-repo-check -s workspace-write --color never "${imgs[@]}" \
      "Use your image generation tool to create ONE image, then save the generated PNG into the current directory as $name.png. $prompt" > "$name.log" 2>&1 < /dev/null
    [ -f "$name.png" ] && echo "   ok $name" || echo "   FAILED $name" ) & }
WHO="The attached image is the character sheet of an ORIGINAL character, the Wanderer (chibi, messy black hair with icy pale-blue highlights and an antenna strand, blue eyes, frayed scarf, long coat, boots)."
SCRAP="Draw FOUR separate torn pieces of sketchbook paper (warm off-white, ragged torn edges, a strip of beige masking tape on one corner of each), each a different shape, roughly the same size, laid out in a 2x2 grid with flat solid pure magenta #FF00FF everywhere between and around them (no shadow on the magenta). On each, an animator's rough working sketch in graphite pencil, with a few confident black-ink lines over it and ONE small accent in red pencil (an arrow, a circle, a tick). Loose, alive, expressive, like pages from a real animator's sketchbook. ABSOLUTELY NO text, letters, numbers or words anywhere. Landscape 3:2 (1536x1024)."
go scraps_1 "$WHO $SCRAP The four sketches: (1) a rough model sheet of the character's head from front, three-quarter and side, with construction circles; (2) design studies of a small glowing red spark: circles with motion arrows and a squash-and-stretch bounce arc; (3) a running man in simple construction shapes, four overlapping run-cycle poses with an arc traced through the head; (4) design roughs of a big rectangular rubber eraser as a menacing character, three angles, smudgy." ref_wanderer.png
go scraps_2 "$WHO $SCRAP The four sketches: (1) an origami crane folding diagram: four small steps with dashed fold lines and curved arrows; (2) a thumbnail of the character riding a paper crane over the sea at night, with a flight-path arrow; (3) a study of a huge curling ocean wave: the lip, the hollow, foam claws, with arrows of the water's motion; (4) quick gesture drawings of the character surfing on a giant calligraphy brush, three poses." ref_wanderer.png
go scraps_3 "$WHO $SCRAP The four sketches: (1) a rough sketch of a huge whale with proportion lines and its open mouth drawn separately; (2) a study of the whale's eye and a small figure swimming beside it for scale; (3) design roughs of a light-sword hilt: three cylinder hilt designs with a small blade stub; (4) duel staging thumbnails: two small figures with crossed swords and a hanging bulb, arrows showing the camera circling." ref_wanderer.png
go scraps_4 "$WHO $SCRAP The four sketches: (1) design roughs of a broomstick and a pointed wizard hat; (2) a loop-the-loop flight path diagram with the character on a broom at three points of the loop; (3) key poses of a spinning overhead soccer kick inside a cone of fire, three poses, with a spiral arrow; (4) a final-pose thumbnail: the character standing holding out a calligraphy brush toward the viewer, with a square seal stamp drawn beside him." ref_wanderer.png
PENCIL="$WHO Redraw him as an animator's rough PENCIL TEST: loose graphite pencil lines over a light blue col-erase pencil underdrawing, visible construction lines, no colour fills (only the icy-blue hair highlight touched in blue pencil), on PLAIN PURE WHITE paper (#FFFFFF, no texture, no shadows, no paper edges). ONLY the character, nothing else in any frame: no animals, no creatures, no props unless named. EIGHT frames in one row, all the same size, feet on one level, evenly spaced, not overlapping. No text, no numbers. Landscape 3:2 (1536x1024). The eight frames, in order:"
go pencil_1 "$PENCIL (1) standing stiffly, arms at sides; (2) surprised, looking up and to the right; (3) lifting one foot for a first step; (4) running to the right, contact pose; (5) running, passing pose; (6) running, both feet off the ground; (7) tumbling in the air upside down, arms flailing; (8) a superhero landing, one knee and one fist down." ref_wanderer.png
go pencil_2 "$PENCIL (1) crouched low against the wind, hair and scarf blown back; (2) kneeling up with a fist raised in joy; (3) standing on a big calligraphy brush like a surfboard, crouched; (4) surfing standing tall, arms spread; (5) swimming underwater, breaststroke, scarf floating; (6) swimming, kicking down; (7) holding a light-sword hilt in both hands, ready stance (draw the blade as a short pencil line); (8) a big overhead sword strike." ref_wanderer.png
go pencil_3 "$PENCIL (1) blocking with the sword held across his body; (2) flying fast on a broomstick wearing a pointed wizard hat; (3) banking hard on the broom; (4) reaching forward from the broom with an open hand; (5) a spinning overhead bicycle kick in mid-air; (6) standing facing the viewer holding out a calligraphy brush; (7) waving goodbye, eyes closed smiling; (8) walking away, seen from behind." ref_wanderer.png
STICK="Die-cut vinyl STICKERS: each one a bold illustration with a THICK clean white border following its outline and a soft glossy highlight, slightly raised like a real sticker, on flat solid pure magenta #FF00FF (no shadow on the magenta). Each sticker a DIFFERENT art style. Big, evenly spaced in one row, not overlapping. No text, letters or numbers. Landscape 3:2 (1536x1024)."
go stickers_1 "$WHO $STICK FOUR stickers: (1) INK: a single bold black brush-ink drop with a small red spark beside it, sumi-e style; (2) PIXEL ART: the character's head in crisp 16-bit pixel art with a pixel heart; (3) CLAYMATION: a little plasticine paper crane in red clay with thumbprints; (4) WATERCOLOUR: a curling blue ocean wave in loose watercolour washes." ref_wanderer.png
go stickers_2 "$WHO $STICK THREE stickers: (1) CHALK: a white chalk line drawing of a whale on a small piece of dark green blackboard; (2) POP-ART COMIC: a jagged comic explosion burst in yellow and red with halftone dots and a blue light-sword crossing it; (3) 1930s RUBBER-HOSE CARTOON: a black-and-white bendy broomstick with a pointed wizard hat, white cartoon gloves holding it, film grain." ref_wanderer.png
wait; echo "== all done"
# ---- round 28b: pop-art comic onomatopoeia for the big impacts
POW="Pop-art COMIC BOOK ONOMATOPOEIA impact effects, like a 1960s comic: each one a big jagged starburst explosion shape (spiky, irregular, layered: a yellow inner burst, a red or cyan outer burst, thick black outlines, Ben-Day halftone dots, a few sharp speed lines) with ONE bold comic word lettered on it in huge chunky slanted 3D comic letters with a thick black outline and a drop shadow. Spell each word EXACTLY as given, letter by letter. Each burst a different shape and colour scheme, all the same size, evenly spaced in a 3x2 grid, not overlapping, on flat solid pure magenta #FF00FF (no shadow on the magenta). Landscape 3:2 (1536x1024)."
go pow_1 "$POW The six words, in order: (1) POW! (2) BAM! (3) WHAM! (4) KRAK! (5) ZAP! (6) BOOM!"
go pow_2 "$POW The six words, in order: (1) SPLASH! (2) GULP! (3) SWOOSH! (4) VMMM (5) CHOMP! (6) SNAP!"
