#!/bin/bash
# Round 29: the cinematic desk (PC): the desk the film lies on, its props, and ink doodles for the paper's margins.
#   scripts/gen-cine.sh [only-name ...]   → art/raw/<name>.png
cd "$(dirname "$0")/../art/raw" || exit 1
JOBS=${JOBS:-5}
ONLY=" $* "
want() { [ "$ONLY" = "  " ] || [[ "$ONLY" == *" $1 "* ]]; }
go() { local name=$1 prompt=$2; shift 2
  want "$name" || return; [ -f "$name.png" ] && return
  while [ "$(jobs -rp | wc -l)" -ge "$JOBS" ]; do sleep 2; done
  local imgs=(); for i in "$@"; do imgs+=("--image=$i"); done
  ( echo "== $name"
    timeout 1500 codex exec --skip-git-repo-check -s workspace-write --color never "${imgs[@]}" \
      "Use your image generation tool to create ONE image, then save the generated PNG into the current directory as $name.png. $prompt" > "$name.log" 2>&1 < /dev/null
    [ -f "$name.png" ] && echo "   ok $name" || echo "   FAILED $name" ) & }
PAINT="Hand-painted look, like background art from a hand-drawn animated film: soft gouache brushwork, warm and atmospheric, NOT a photograph, NOT 3D render."
PROP="$PAINT Seen from DIRECTLY ABOVE (top-down, flat lay), lit by a warm lamp from the upper left with a soft short shadow painted under each object. On flat solid pure magenta #FF00FF everywhere around the objects (no shadow on the magenta, no table). Big, evenly spaced in ONE horizontal row, not overlapping, not touching. No text, no logos, no labels. Landscape 3:2 (1536x1024)."
go desk_top "$PAINT A wide TOP-DOWN view (camera directly above) of an animator's old wooden drawing desk at night: rich dark walnut planks with grain, worn edges, faint old ink stains and pencil marks, a pool of warm golden lamp light in the middle fading to deep warm shadow at the edges and corners. The middle of the desk is EMPTY and clear (a sheet of paper will be placed there later). NO objects at all on the desk: no paper, no pencils, no cups, nothing. No text. Landscape 3:2 (1536x1024)."
go props_1 "$PROP THREE long objects, each lying VERTICALLY (pointing up and down) side by side: (1) a long hexagonal wooden pencil painted red with a black tip end and a sharpened graphite point; (2) a Japanese bamboo calligraphy brush with a soft black-wet bristle tip and a little hanging loop; (3) an animator's aluminium PEG BAR: a flat metal strip with one round peg in the middle and two flat pegs near its ends."
go props_2 "$PROP THREE objects: (1) a round black inkstone dish with a pool of wet glossy black ink and an ink stick resting on it; (2) a worn, chunky PINK rubber eraser block, its corners rubbed round, grey smudges on it; (3) a white ceramic coffee mug seen from directly above, half full of dark coffee, a brown coffee ring stain beside it."
go doodles "Art style: rough dry-brush black sumi ink on paper, confident and expressive, like an ink master's quick sketch in a sketchbook margin, with ONE small vermilion red accent in each. FOUR separate LARGE ink doodles in ONE horizontal row, evenly spaced, not overlapping, each a single strong shape (no small repeated things, no flocks, no crowds): (1) a tall wind-bent pine tree; (2) a far mountain ridge with a red sun circle above it; (3) a single paper crane in flight drawn in a few strokes; (4) a big curling wave crest. Flat solid pure magenta #FF00FF everywhere around them (no paper texture, no shadow). No text. Landscape 3:2 (1536x1024)."
wait; echo "== all done"

# ---- the desk, take two: lively, messy, funky (the owner: "not lonely dark brown… lively, active and fun")
FUNK="A wide TOP-DOWN view (camera directly above, flat lay) of a joyful, messy, lived-in ARTIST'S DESK in bright daylight, hand-painted illustration style with bold confident shapes and saturated colour, fun and full of energy. The MIDDLE of the desk is EMPTY and clear (a sheet of paper will be placed there later) and the mess lives round the edges. Use a FEW BIG BOLD shapes, not lots of tiny objects: no clusters of small things, no rows of little items, no tiny scattered dots. No paper sheets, no text, no letters, no logos, no people. Landscape 3:2 (1536x1024)."
go desk_funk_a "$FUNK The desk top is a bright TEAL self-healing cutting mat with a faint grid, with a few HUGE splashes and drips of paint in vermilion red, sunny yellow and cobalt blue, two long strips of patterned washi tape stuck across the corners, a big dried coffee ring, a fat swoosh of black ink from a brush."
go desk_funk_b "$FUNK The desk itself is old wood PAINTED in bold colour blocks (mustard yellow, coral pink, teal) that have been chipped and painted over, covered in big confident paint splatters, a giant painted red circle (a sun) in one corner, a few big black marker doodles of stars and squiggles drawn straight on the desk, a large rainbow smear where a brush was wiped."
go desk_funk_c "$FUNK A pop-art comic DESK: the surface is cream paper-white desk covered in bold black marker doodles and cartoon squiggles drawn straight onto it, BIG Ben-Day halftone dot patches in red and cyan, a couple of huge yellow and red paint splats with thick black outlines, a big pink sticky-note shape, and one enormous cartoon ink splash, like a comic book page come to life."
wait; echo "== all done (take two)"

# ---- the desk, take three: REAL (photographic), but lively and funky — a working artist's desk, not a cartoon
REAL="A real PHOTOGRAPH, top-down (camera directly above, flat lay), of a working artist's desk in bright natural daylight from a window: lively, colourful, joyful and lived-in, like a real illustrator's studio desk on a creative instagram. Photorealistic, natural textures, soft real shadows, shot on a full-frame camera. The MIDDLE of the desk is EMPTY and clear (a sheet of paper will be placed there later); the life and mess sit round the edges and corners. Prefer a few BIG colourful things over lots of tiny ones: no piles of little objects, no scattered beads, pins or confetti. No paper sheets in the middle, no text, no logos, no brand names, no people, no hands. Landscape 3:2 (1536x1024)."
go desk_real_a "$REAL The desk is old wood COVERED in years of real dried paint splatters and drips in every colour (vermilion, cobalt, sunflower yellow, teal, pink), with a big wooden palette of fresh oil-paint blobs in one corner, a glass jar of used paintbrushes, a couple of squeezed paint tubes, and a strip of masking tape."
go desk_real_b "$REAL A big green self-healing cutting mat on a white desk, with bright rolls of washi tape, a fan of colour swatch cards, chunky felt markers, a small potted plant seen from above, a colourful ceramic mug, and a few bold vinyl stickers stuck right onto the mat."
go desk_real_c "$REAL A raw plywood workbench of a street artist: colourful spray-paint overspray clouds and stencil marks sprayed straight onto the wood, a few spray cans lying on their side, paint-marker tags and doodles drawn on the wood, a roll of gaffer tape, a splash of neon pink and electric blue."
wait; echo "== all done (take three)"

# ---- the owner picked B, "but remove the girly things": the same photo, edited
go desk_real_b2 "Edit the attached photograph: keep it EXACTLY the same photo (same top-down camera, same green cutting mat in the middle, same white desk, same daylight and shadows, same layout and photorealism), but REMOVE the girly things: remove the flower stickers, the lemon sticker and the rainbow sticker from the mat (leave clean mat there); replace the pink and pastel washi tape rolls with plain black and kraft-brown tape rolls; replace the floral-pattern mug with a plain matte black ceramic mug of coffee; make the colour swatch fan bold primary colours (red, yellow, blue, green, black) with no pink or lilac. Keep the plant, the markers, the pencil pot, the watercolour tin and the orange scissors. No text, no logos." desk_real_b.png
wait; echo "== all done (b2)"

# ---- round 30: story on the desk — crumpled drafts that pile up, and the knock on the page
go crumple "A real PHOTOGRAPH, top-down (camera directly above), of FOUR separate crumpled-up balls of white sketch paper, each scrunched into a loose ball, with fragments of black ink sketch lines and a little red pencil visible on the creases, soft natural daylight from the upper left with a soft short shadow painted under each. Photorealistic. Flat solid pure magenta #FF00FF everywhere around them (no table, no shadow on the magenta). Big, evenly spaced in ONE horizontal row, not touching. No text. Landscape 3:2 (1536x1024)."
go knock "The attached image is the character sheet of an ORIGINAL character, the Wanderer (chibi, messy black hair with icy pale-blue highlights and an antenna strand, blue eyes, frayed scarf, long black coat, boots). Draw the SAME character in rough dry-brush black ink, wearing a tall pointed black wizard hat, sitting on a wooden broomstick. THREE frames, the same size, evenly spaced in one row, not overlapping: (1) looking around wide-eyed and startled, as if he has just noticed something huge outside his world, one hand up; (2) leaning toward the viewer and KNOCKING with his knuckles on an invisible glass pane in front of him, fist forward toward the viewer, curious face; (3) the same knock, fist pulled back, about to knock again, mouth open saying 'hello?'. Flat solid pure magenta #FF00FF everywhere that is not the drawing; no glass drawn, no text, no speed lines. Landscape 3:2 (1536x1024)." ref_wanderer.png
wait; echo "== all done (r30)"
